language: php

sudo: false

env:
  global:
    - COMPOSER_MEMORY_LIMIT="-1"

matrix:
    include:
      - php: 7.0
        env: COMPOSER_ARGS=""
      - php: 7.1
        env: COMPOSER_ARGS=""
      - php: 7.2
        env: COMPOSER_ARGS=""
      - php: 7.4
        env: COMPOSER_ARGS=""
      - php: 8.0
        env: COMPOSER_ARGS=""

      - php: 7.0
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.1
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.2
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.4
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 8.0
        env: COMPOSER_ARGS="--prefer-lowest"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - bin/phpunit
